const { OPERATIONS, RESOURCES } = require('../utils/constant/privilege-constant');

const STATIC_ROLES = Object.freeze({
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
});

const SUPER_ADMIN_RESOURCE_OPERATIONS = {
  [RESOURCES.PROFESSION]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.LANGUAGE]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.TRIVIA_TYPES]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.SOCIAL_LINKS]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.GENRE]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.CELEBRITY]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [RESOURCES.SECTION_TYPES]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.SECTION_TEMPLATE]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.USERS]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE]
};

const ADMIN_RESOURCE_OPERATIONS = {
  [RESOURCES.LANGUAGE]: [OPERATIONS.READ],
  [RESOURCES.GENRE]: [OPERATIONS.READ],
  [RESOURCES.CELEBRITY]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [RESOURCES.SECTION_TYPES]: [OPERATIONS.READ],
  [RESOURCES.SECTION_TEMPLATE]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE],
  [RESOURCES.USERS]: [OPERATIONS.CREATE, OPERATIONS.READ, OPERATIONS.UPDATE, OPERATIONS.DELETE]
};

const STATIC_PRIVILEGES = {
  [STATIC_ROLES.SUPER_ADMIN]: {
    role: STATIC_ROLES.SUPER_ADMIN,
    permissions: Object.entries(SUPER_ADMIN_RESOURCE_OPERATIONS).map(([resource, operations]) => ({
      resource,
      operations
    })),
    isActive: true,
    isLocked: true 
  },
  
  [STATIC_ROLES.ADMIN]: {
    role: STATIC_ROLES.ADMIN,
    permissions: Object.entries(ADMIN_RESOURCE_OPERATIONS).map(([resource, operations]) => ({
      resource,
      operations
    })),
    isActive: true,
    isLocked: true 
  }
};

module.exports = {
  
  STATIC_ROLES,
  SUPER_ADMIN_RESOURCE_OPERATIONS,
  ADMIN_RESOURCE_OPERATIONS,
  STATIC_PRIVILEGES
};