const { OPERATIONS, RESOURCES } = require('../utils/constant/privilege-constant');

const STATIC_ROLES = Object.freeze({
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
});

const STATIC_MODULE_ROLE = Object.freeze({
  [STATIC_ROLES.SUPER_ADMIN]: [RESOURCES.ROLE_MANAGEMENT, RESOURCES.USER_MANAGEMENT], 
  [STATIC_ROLES.ADMIN]: [RESOURCES.ROLE_MANAGEMENT, RESOURCES.USER_MANAGEMENT], 

});

const SUPER_ADMIN_RESOURCE_OPERATIONS = {
  [RESOURCES.PROFESSION]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.LANGUAGE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.TRIVIA_TYPE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.SOCIAL_LINK]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.GENRE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.CELEBRITY]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [RESOURCES.SECTION_TYPE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.SECTION_TEMPLATE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE]
};

const ADMIN_RESOURCE_OPERATIONS = {
  [RESOURCES.LANGUAGE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.TRIVIA_TYPE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.SOCIAL_LINK]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.GENRE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.CELEBRITY]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE, OPERATIONS.PUBLISH],
  [RESOURCES.SECTION_TYPE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE],
  [RESOURCES.SECTION_TEMPLATE]: [OPERATIONS.ADD, OPERATIONS.EDIT, OPERATIONS.DELETE]
};


const STATIC_PRIVILEGES = {
  [STATIC_ROLES.SUPER_ADMIN]: {
    role: STATIC_ROLES.SUPER_ADMIN,
    permissions: Object.entries(SUPER_ADMIN_RESOURCE_OPERATIONS).map(([resource, operations]) => ({
      resource,
      operations
    })),
    isActive: true,
    isLocked: true 
  },
  
  [STATIC_ROLES.ADMIN]: {
    role: STATIC_ROLES.ADMIN,
    permissions: Object.entries(ADMIN_RESOURCE_OPERATIONS).map(([resource, operations]) => ({
      resource,
      operations
    })),
    isActive: true,
    isLocked: true 
  }
};

module.exports = {
  STATIC_ROLES,
  SUPER_ADMIN_RESOURCE_OPERATIONS,
  ADMIN_RESOURCE_OPERATIONS,
  STATIC_PRIVILEGES,
  STATIC_MODULE_ROLE
};